### PR TITLE
Change current week number to Iso 8601 Week Number

### PR DESCRIPTION
**Pull request by rajaomariajaona**
[https://en.wikipedia.org/wiki/Week#Week_numbering](url)

### CODE REVIEW

**Comment by jama5262** [comment]
Hi, thanks for your contribution. Now about the PR, is there a reason for it? I did not understand

**Comment by rajaomariajaona** [comment]
I have recently used Jiffy and I saw that the week number did not give the correct number according to the ISO 8601
Example:
2019-12-31 and 2019-12-30 should  return 1 instead 53

**Comment by talamaska** [comment]
It's not only that, the week is starting from Sunday???

**Comment by jama5262** [comment]
A new breaking change has been released with major changes, please open another PR

**Pull request closed without merging**
