### PR TITLE
Add SK and CS locales

### PR DESCRIPTION
**Pull request by tomaschyly**
**What does this PR do?**

I have added SK and CS locales

**Types of changes**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Maintenance change (non-breaking change such as upgrading a dependency, refactoring, or making a lint fix)
- [x] Documentation update
- [ ] Breaking change (a fix or feature that would cause existing functionality to change)

**Checklist**

- [x] Wrote additional tests, if needed
- [x] All tests have passed
- [x] I have updated the documentation accordingly, if needed.

### CODE REVIEW

**Comment by jama5262** [comment]
@tomaschyly please add tests for these two locales here [locales_test.dart](https://github.com/jama5262/jiffy/blob/master/test/src/locale/locales/locales_test.dart)

You can also follow this discussion https://github.com/jama5262/jiffy/discussions/231

**Comment by tomaschyly** [comment]
@jama5262 I have added tests for these two locales

**Comment by tomaschyly** [comment]
@jama5262 do you plan to merge this, or is there some issue?

**Review by jama5262 — CHANGES_REQUESTED** [review]
Hey @tomaschyly , thanks for making the changes, just on more test to add, 

As per the instruction from this discussion here https://github.com/jama5262/jiffy/discussions/231, you also need to add your two locales in this test here https://github.com/jama5262/jiffy/blob/master/test/src/locale/supported_locales_test.dart#L6-L21

And once you've made the changes, please, re-request a review so that the GitHub actions workflow will run

**Review by jama5262 — APPROVED** [review]

**Pull request merged**
