### PR TITLE
updated intl dependency

### PR DESCRIPTION
**Pull request by AlessioValentiniAesys**
Updated int dependency to support flutter 2.0.

### CODE REVIEW

**Comment by jama5262** [comment]
@AlessioValentiniAesys The intl dependency has been updated here #93 and the changes will be publish by today that is version `4.0.0` of Jiffy. For now I will close this PR

**Comment by AlessioValentiniAesys** [comment]
ok thanks

**Comment by proninyaroslav** [comment]
Hope you will release it soon.

**Comment by jama5262** [comment]
@proninyaroslav To be released by the end of today

**Pull request closed without merging**
