### PR TITLE
added Norwegian Bokmål (nb) language

### PR DESCRIPTION
**Pull request by zeusbaba**

### CODE REVIEW

**Comment by jama5262** [comment]
@zeusbaba Hi, thanks for your contribution. A few changes I would request
1. Please send PRs to `develop` branch and not the `master` branch
2. Write tests for your locale

**Comment by zeusbaba** [comment]
fyi. just updated with tests and base branch.

**Comment by jama5262** [comment]
@zeusbaba Thanks but the travis CI test failed because of not formating your code, please use dart-formater for all the files you added or changed. **Dart formatting is required so that the tests could pass**

Use this to check for any none formatted files

`dartanalyzer lib test example && dartfmt -n --set-exit-if-changed lib test`

**Comment by zeusbaba** [comment]
thanks for your feedback. I'll do that soon together with a fix.   
btw I just realized that there's another #61  for Norwegian language, apologies i missed that.

**Pull request merged**
