### PR TITLE
change version intl to 0.18.0

### PR DESCRIPTION
**Pull request by nguyenxdat**
**What does this PR do?**

A clear and concise description of what this PR solves.

**Types of changes**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change)

**Screenshots**

**Checklist**

- [ ] Directed the PR to `develop` branch and not the `master` branch
- [ ] Wrote additional tests, if needed
- [ ] All tests have passed
- [ ] I have updated the documentation accordingly, if needed.

### CODE REVIEW

**Comment by onurbultan** [comment]
Please approve this :)

**Comment by dgilperez** [comment]
Hi guys any update? Is the package actively supported? Any workaround?

**Comment by mikhael28** [comment]
+1 on this!

**Review by dancamdev — APPROVED** [review]
It looks like I'm allowed to Review the changes for whatever reason? Well, it's just a dependency upgrade so let's finally merge it!

**Comment by dancamdev** [comment]
@jama5262 Are you planning on merging this, is there some reason it won't?

**Review by jama5262 — APPROVED** [review]

**Comment by jama5262** [comment]
Resolves #167

**Comment by jama5262** [comment]
Intl v0.18.0 released

**Pull request merged**
